# Funding options for Beaconchain Horizon

github: [beaconchain-horizon]
custom: ['https://beaconchain.us/donate', 'https://beaconchain-horizon.github.io/Beaconchain.us/']

# حذف شده به دلیل عدم وجود حساب فعال:
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# liberapay: 
# issuehunt: 
# otechie: